include /opt/theos/makefiles/common.mk

export SYSROOT = /opt/theos/sdks/iPhoneOS11.2.sdk

TWEAK_NAME = ac1d
ac1d_FILES = Tweak.xm
ac1d_PRIVATE_FRAMEWORKS = AppSupport UIKit MediaRemote MediaPlayer SpringBoardServices CoreFoundation

include /opt/theos/makefiles/tweak.mk
